# docker-composeバージョンの宣言
# https://docs.docker.com/compose/compose-file/
version: '3.7'
x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  postgres_django:
    restart: always
    build: containers/postgresql
    container_name: postgres_django
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - django_postgres_data:/var/lib/postgresql/data
    #      - ./docker/postgresql/postgresql.conf:/etc/postgresql.conf
    #      - ./docker/01_create_db.sql:/docker-entrypoint-initdb.d/01_create_db.sql
    #      - ./docker/02_django_db.sql:/docker-entrypoint-initdb.d/02_django_db.sql
    ports:
      - "5432"
    logging: *default-logging

  web_django:
    restart: always
    build: containers/django
    container_name: web_django
    environment:
    # --max-requests 1は開発中にファイルを変更しても反映されないのでさせるために付与。
    # 付けない場合はファイル更新を通知するために下記をする必要がある
    # docker exec -it django_web pgrep gunicorn
    # docker exec -it django_web kill -HUP [↑で確認した番号]
    command: bash -c "sleep 5; gunicorn config.wsgi --workers 2 --bind 0.0.0.0:8000 --max-requests 1"
    volumes:
      - ./app:/usr/src/app
    ports:
      - "80"
    logging: *default-logging

#  django_redis:
#    restart: always
#    image: redis:alpine
#    container_name: "django_redis"
#    ports:
#      - "6379"
#    logging: *default-logging

volumes:
  htpasswd:
  vhost:
  html:
  django_postgres_data:
